name: Continuous Integration
on: [ push ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - run: npm install

      - run: npm run build

      - uses: JS-DevTools/npm-publish@0fd2f4369c5d6bcfcde6091a7c527d810b9b5c3f # v4
        with:
          access: public
          token: ${{ secrets.NPM_TOKEN }}
